name: Lint Dockerfile

on:
  push:
    branches: 
     - "**"

jobs:
  linter:
  
    runs-on: ubuntu-latest
    container: hadolint/hadolint:latest-debian

    steps:

      - uses: actions/checkout@v2

      - name: Lint Dockerfile
        run : hadolint $PWD/.hadolint.yaml Dockerfile
